packages:
  - packages/*

overrides:
  "preact@<10.27.3": "^10.27.3"
  "devalue@<5.6.4": "^5.6.4"
  "fast-uri@<3.1.2": "^3.1.2"

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild

patchedDependencies:
  '@pierre/diffs@1.1.4': patches/@pierre__diffs@1.1.4.patch
